---
title: "Data science per psicologi - demo 13.01"
author: "Corrado Caudek"
date: "`r format(Sys.Date())`"
output:
  html_document:
    theme: readable
    code_download: true
---

```{r}
suppressPackageStartupMessages({
  library("here")
  library("tidyverse")
  library("scales")
  library("bayesplot")
  library("distrEx")
})

theme_set(bayesplot::theme_default(base_size = 12))
bayesplot::color_scheme_set("gray")
set.seed(84735)

knitr::opts_chunk$set(
  collapse = TRUE,
  tidy = 'styler',
  fig.width = 6,
  fig.asp = 0.618 # 1 / phi
)
```

# Esercizi sulle funzioni di densità

## Esercizio 1

Sia $X$ una variabile continua con funzione di densità $f(x) = 3x^2$, $0 < x < 1$. Si fornisca un grafico di tale funzione e si trovi la probabilità $p(0.14 <= x <= 0.71)$.

```{r}
f <- function(x) 3 * x^2
integrate(f, lower = 0.14, upper = 0.71)
```

```{r}
x <- seq(0, 1, length.out = 1e3)
tibble(x = x, y = f(x)) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_line()
```

## Esercizio 2

Per i dati dell'esercizio 1, si trovino il valore atteso e la varianza di $X$.

```{r}
X <- AbscontDistribution(d = f, low1 = 0, up1 = 1)
```


```{r}
E(X)
```

```{r}
var(X)
```

Possiamo anche replicare il risultato dell'esercizio 1 nel modo seguente:

```{r}
p(X)(0.71) - p(X)(0.14)
```


## Informazioni sulla sessione di lavoro

```{r}
utils::sessionInfo()
```


